### PR TITLE
Fix handling of aliases

### LINKED ISSUE #63: target-determinator does not evaluate aliases as changed
In my project I have a setup akin to:

```
py_library(
  name = "foo"
  ...
)

alias(name = "bar", actual = ":foo")
```

When I've made changes that invalidate foo and running:
```
target-determinator -targets //foo HEAD~1
```
I observe, correctly that `//foo` has been identified as a changed target.

However, for the _same_ changeset that invalidates foo and running:
```
target-determinator -targets //bar HEAD~1
```
`//bar` is not listed as changed.

### PR DESCRIPTION
**Pull request by illicitonion**
Work around https://github.com/bazelbuild/bazel/issues/17749 and https://github.com/bazelbuild/bazel/issues/18421

Fixes #63

### CODE REVIEW

File: tests/integration/java/com/github/bazel_contrib/target_determinator/integration/TestdataRepo.java [hunk 1]
```diff
@@ -15,7 +15,7 @@ public class TestdataRepo {
   public static TestdataRepo create() throws Exception {
     Path path = Files.createTempDirectory("target-determinator-testdata");
     Git.cloneRepository()
-        .setURI("https://github.com/bazel-contrib/target-determinator-testdata.git")
+        .setURI("https://github.com/illicitonion/target-determinator-testdata.git")
```
Comment (illicitonion) [inline tests/integration/java/com/github/bazel_contrib/target_determinator/integration/TestdataRepo.java:18]: TODO: Push these to bazel-contrib and update this code back before merging

**Review by sitaktif — APPROVED** [review]
